-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 15:22:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CSDdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CSDdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSDdb` DEFAULT CHARACTER SET utf8 ;
USE `CSDdb` ;

-- -----------------------------------------------------
-- Table `mydb`.`experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSDdb`.`experiment` (
  `idexperiment` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idexperiment`),
  UNIQUE INDEX `idexperiment_UNIQUE` (`idexperiment` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mother`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSDdb`.`mother` (
  `idmother` INT NOT NULL AUTO_INCREMENT,
  `allel1` INT NOT NULL,
  `allel2` INT NOT NULL,
  `motherAppId` INT NOT NULL,
  `experiment_idexperiment` INT NOT NULL,
  PRIMARY KEY (`idmother`),
  UNIQUE INDEX `idmother_UNIQUE` (`idmother` ASC),
  INDEX `fk_mother_experiment1_idx` (`experiment_idexperiment` ASC),
  CONSTRAINT `fk_mother_experiment1`
    FOREIGN KEY (`experiment_idexperiment`)
    REFERENCES `CSDdb`.`experiment` (`idexperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSDdb`.`data` (
  `iddata` INT NOT NULL AUTO_INCREMENT,
  `currentGen` INT NOT NULL,
  `age` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `mother_idmother` INT NOT NULL,
  PRIMARY KEY (`iddata`),
  UNIQUE INDEX `iddata_UNIQUE` (`iddata` ASC),
  INDEX `fk_data_mother_idx` (`mother_idmother` ASC),
  CONSTRAINT `fk_data_mother`
    FOREIGN KEY (`mother_idmother`)
    REFERENCES `CSDdb`.`mother` (`idmother`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSDdb`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSDdb`.`info` (
  `idinfo` INT NOT NULL AUTO_INCREMENT,
  `generationNum` INT NOT NULL,
  `size` INT NOT NULL,
  `allelPoolSize` INT NOT NULL,
  `dip` FLOAT NOT NULL,
  `swarmingDist` FLOAT NOT NULL,
  `droneDist` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  `experiment_idexperiment` INT NOT NULL,
  PRIMARY KEY (`idinfo`),
  UNIQUE INDEX `idinfo_UNIQUE` (`idinfo` ASC),
  INDEX `fk_info_experiment1_idx` (`experiment_idexperiment` ASC),
  CONSTRAINT `fk_info_experiment1`
    FOREIGN KEY (`experiment_idexperiment`)
    REFERENCES `CSDdb`.`experiment` (`idexperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
